
export LANG=en_US.UTF-8
export LC_ALL=$LANG

export HOMEBREW_GITHUB_API_TOKEN=6d72a0e4641e0a3f825112ff670dd61c485a824d

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

[[ -s "$HOME/.zprezto/runcoms/zlogin" ]] && source "$HOME/.zprezto/runcoms/zlogin"

