export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

export EDITOR=/usr/local/bin/vim

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0)

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

unsetopt share_history

alias git=/usr/local/bin/git
alias google-chrome=/Applications/Google\\\ Chrome.app/Contents/MacOS/Google\\\ Chrome
alias groovysh="groovysh -Djava.awt.headless=true"
alias weather="curl wttr.in/Berlin"
alias jrnl="vim +'normal Go' +'r!date' ~/journal"

. ~/.nvm/nvm.sh

export SDKROOT=`xcrun -sdk macosx10.14 --show-sdk-path`
export SDK_DIR=$SDKROOT
export SDK_NAME="macosx10.13"

[[ -s "$HOME/.zprezto/runcoms/zshrc" ]] && source "$HOME/.zprezto/runcoms/zshrc"
[[ -s "$HOME/.zprezto/init.zsh" ]] && source "$HOME/.zprezto/init.zsh"

setopt no_share_history
unsetopt share_history
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# added by travis gem
[ -f /Users/dennis/.travis/travis.sh ] && source /Users/dennis/.travis/travis.sh

