---
- hosts: all
  vars:
    home: /Users/dennis

  tasks:
    - name: Install packages with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - ack
        - fd
        - fswatch
        - ghi
        - git
        - gpg
        - jq
        - leiningen
        - maven
        - mongodb
        - neovim/neovim/neovim
        - nmap
        - nvm
        - pinentry-mac
        - rpm
        - travis
        - vim
        - wget
        - zsh
        - z

    - name: Install packages with homebrew casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - adium
        - atom
        - dash
        - discord
        - docker
        - evernote
        - firefox
        - font-dejavu-sans-mono-for-powerline
        - google-chrome
        - google-hangouts
        - insomnia
        - intellij-idea
        - iterm2
        - keepassx
        - licecap
        - robo-3t
        - slack
        - sonos
        - spotify
        - steam
        - sublime-text
        - textmate
        - viscosity
        - visual-studio-code
        - vlc
        - wireshark

    - name: Checkout prezto (instantly awesome zsh)
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=/Users/dennis/.zprezto recursive=yes track_submodules=yes force=yes

    - name: Symlink dotfiles
      file: path={{ home }}/.{{ item }} src={{ home }}/.ws/dotfiles/{{ item }} state=link
      with_items:
        - git_commit_msg
        - gitconfig
        - vimrc
        - zlogin
        - zpreztorc
        - zshrc

    - name: Checkout Vundle (vim plugin manager)
      git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/Users/dennis/.vim/bundle/Vundle.vim recursive=yes

    - name: Install Vundle plugins
      shell: vim +PluginInstall +qall

    - name: Checkout powerline9k (zsh theme)
      git: repo=https://github.com/bhilburn/powerlevel9k.git dest=/Users/dennis/.zsh/powerlevel9k
