---
- hosts: all
  vars:
    home: /Users/dennis

  tasks:  
    - name: Install packages with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - ack
        - atom
        - fswatch
        - ghi
        - git
        - jq
        - leiningen
        - maven
        - neovim/neovim/neovim
        - nmap
        - nvm
        - vim
        - wget

    - name: Install packages with homebrew casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - adium
        - dash
        - discord
        - docker
        - firefox
        - google-chrome
        - google-hangouts
        - intellij-idea
        - keepassx
        - licecap
        - robomongo
        - slack
        - sonos
        - spotify
        - steam
        - sublime-text
        - textmate
        - viscosity
        - vlc
        - wireshark
        - zoomus

    - name: Checkout prezto (instantly awesome zsh)
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=/Users/dennis/.zprezto recursive=yes

    - name: Symlink dotfiles
      file: path={{ home }}/.{{ item }} src={{ home }}/.ws/dotfiles/{{ item }} state=link
      with_items:
        - git_commit_msg
        - gitconfig
        - vimrc
        - zlogin
        - zpreztorc
        - zshrc

 
