---
- hosts: all
  vars:
    home: /Users/dennis

  tasks:  
    - name: Install packages with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - git
        - vim
        - nmap
        - nvm
        - leiningen
        - jq
        - maven
        - ack

    - name: Install packages with homebrew casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - google-chrome
        - firefox
        - licecap
        - google-hangouts
        - slack
        - sublime-text
        - textmate
        - spotify
        - steam
        - intellij-idea
        - adium
        - docker
        - sonos
        - viscosity
        - vlc

    - name: Checkout prezto (instantly awesome zsh)
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=/Users/dennis/.zprezto recursive=yes

    - name: Symlink dotfiles
      file: path={{ home }}/.{{ item }} src={{ home }}/.ws/dotfiles/{{ item }} state=link
      with_items:
        - git_commit_msg
        - gitconfig
        - vimrc
        - zlogin
        - zshrc
        - zpreztorc

 
